/*++

Copyright (c) 2016 Minoca Corp. All Rights Reserved

Module Name:

    version.h

Abstract:

    This header contains generated version information.
    This file is automatically generated.

Author:

    Minoca Build 20-May-2016

--*/

//
// ---------------------------------------------------------------- Definitions
//

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_REVISION 0
#define VERSION_RELEASE SystemReleaseFinal
#define VERSION_SERIAL 1418
#define VERSION_BUILD_STRING "e85b4a1 May 20 2016 11:22:26"

#define VERSION_BUILD_TIME 485461346
#define VERSION_BUILD_TIME_STRING "May 20 2016 11:22:26"

//
// The full commit number string.
//

#define VERSION_COMMIT_STRING "e85b4a1807d0cba4f03fd6460d4a89794f0467d9"

//
// The abbreviated commit number string.
//

#define VERSION_COMMIT_ABBREVIATED "e85b4a1"

//
// An integer of the first 32 bits of the commit.
//

#define VERSION_COMMIT_NUMBER 0xe85b4a18

//
// The current branch name.
//

#define VERSION_BRANCH "master"

//
// The user name of the soul doing the building.
//

#define VERSION_BUILD_USER "Minoca"

//
// The license under which the software is released.
//

#define VERSION_LICENSE "\nThis software is licensed under the the terms of the GNU General Public License v3."

