/*++

Copyright (c) 2016 Minoca Corp. All Rights Reserved

Module Name:

    version.h

Abstract:

    This header contains generated version information.
    This file is automatically generated.

Author:

    Minoca Build 18-May-2016

--*/

//
// ---------------------------------------------------------------- Definitions
//

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_REVISION 0
#define VERSION_RELEASE SystemReleaseFinal
#define VERSION_SERIAL 1412
#define VERSION_BUILD_STRING "9124ccb May 18 2016 10:56:22"

#define VERSION_BUILD_TIME 485286982
#define VERSION_BUILD_TIME_STRING "May 18 2016 10:56:22"

//
// The full commit number string.
//

#define VERSION_COMMIT_STRING "9124ccb935d5ba86680f05c0fd6250fb3ef518a9"

//
// The abbreviated commit number string.
//

#define VERSION_COMMIT_ABBREVIATED "9124ccb"

//
// An integer of the first 32 bits of the commit.
//

#define VERSION_COMMIT_NUMBER 0x9124ccb9

//
// The current branch name.
//

#define VERSION_BRANCH "master"

//
// The user name of the soul doing the building.
//

#define VERSION_BUILD_USER "Minoca"

//
// The license under which the software is released.
//

#define VERSION_LICENSE "\nThis software is licensed under the the terms of the GNU General Public License v3."

