/*++

Copyright (c) 2016 Minoca Corp. All Rights Reserved

Module Name:

    version.h

Abstract:

    This header contains generated version information.
    This file is automatically generated.

Author:

    Minoca Build 20-May-2016

--*/

//
// ---------------------------------------------------------------- Definitions
//

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_REVISION 0
#define VERSION_RELEASE SystemReleaseFinal
#define VERSION_SERIAL 1416
#define VERSION_BUILD_STRING "0fbdd5e May 20 2016 10:56:02"

#define VERSION_BUILD_TIME 485459762
#define VERSION_BUILD_TIME_STRING "May 20 2016 10:56:02"

//
// The full commit number string.
//

#define VERSION_COMMIT_STRING "0fbdd5efeaf2e2e88cbd93232fff865557819fb7"

//
// The abbreviated commit number string.
//

#define VERSION_COMMIT_ABBREVIATED "0fbdd5e"

//
// An integer of the first 32 bits of the commit.
//

#define VERSION_COMMIT_NUMBER 0x0fbdd5ef

//
// The current branch name.
//

#define VERSION_BRANCH "master"

//
// The user name of the soul doing the building.
//

#define VERSION_BUILD_USER "Minoca"

//
// The license under which the software is released.
//

#define VERSION_LICENSE "\nThis software is licensed under the the terms of the GNU General Public License v3."

